version: "3"

services:
  namecheap-ddns:
    image: sn0am/namecheap-ddns
    container_name: namecheap-ddns
    environment:
    -  host=$host
    -  domain=$domain
    -  ddns_password=$ddns_password
    -  url_to_check_public_ip=$url_to_check_public_ip
    -  ddns_update_interval=$ddns_update_interval
    restart: unless-stopped
